### ISSUE TITLE
Outlook 365 startssl

### ISSUE THREAD

**Issue by nightrayx** [ladybirdweb/faveo-helpdesk#7192] opened 2022-08-31 23:19 UTC
- Faveo Version : #.#.#
- PHP version :
- Database Driver & Version :
- Server specification :

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by nightrayx** [comment] 2022-08-31 23:20
Unable to find the socket transport "starttsl"

**Comment by bhanu2217** [comment] 2023-03-21 05:48
Please try Faveo Helpdesk Community version 2.0.0 and let us know if the issue is still occurring. For now closing the issue.

**Closed by bhanu2217** 2023-03-21 05:48 UTC
