### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by alexisskeates** [ladybirdweb/faveo-helpdesk#7] opened 2015-12-11 15:41 UTC
I've pulled the latest version from git onto my ubuntu webserver. I have made sure the following are installed and enabled:

PHP >= 5.5.9
OpenSSL PHP Extension
PDO PHP Extension
Mbstring PHP Extension
Tokenizer PHP Extension

When I browse to the url that points to my webserver the installer redirects from http://url to http://url/step1 and at that point I get a 404 url not found.

I've had a look and this folder does not exists so I assume the installer creates this it's self, but it appears not to be doing this.

Any suggestions on how to resolve this would be great.

**Comment by sujit223** [comment] 2015-12-14 06:15
I have looked into your issue and found that there are some Apache configuration issue on your server. Need to look into your php info file to solve it.

**Comment by bhanu2217** [comment] 2015-12-14 06:19
Please enable Apache mod_rewrite module

**Comment by ayurmedia** [comment] 2015-12-14 20:40
does not support database config ports other than 3306, had to change config-file manually.

**Comment by ayurmedia** [comment] 2015-12-14 20:49
you have to disable asp-tags in php-ini for it to work because of conflcts in the template-system. <% %>

**Comment by bhanu2217** [comment] 2015-12-15 10:48
We tried on php 5.5.3 with asp_tags on/off both cases and the Faveo project works fine either ways? it didn't impact Faveo. what version of PHP are you using?

**Comment by alexisskeates** [comment] 2015-12-15 11:08
Does this mean you have managed to get it to work running on Ubuntu server? If so do you have any specific settings you used to get it running?

**Comment by bhanu2217** [comment] 2015-12-15 11:17
We have tested on Centos OS 6, shared server using cPanel. I can create one cPanel account for you for testing on our server, need your domain details to match to our server. you can email on support@ladybirdweb.com with your domain name and i will setup for you for testing. Faveo needs no special setting beyond Laravel framework requirement. Check server requirement here http://laravel.com/docs/5.0 We will see in few weeks try and see if we can release ready images of Faveo to install on virtual machines.

**Comment by bhanu2217** [comment] 2015-12-15 11:20
You can also give us your server SSH details also and we can try and check it.

**Comment by ayurmedia** [comment] 2015-12-15 12:21
Are you crazy? I don’t give you ssh accounts. i can give you details about linux, php, apache and mysqlv-versions if this helps. 

apache 1.x 
php5.4 to php5.6 (currently using 5.6)
mysql5.6 running on localhost: 3308 (dev , vs. live)
linux gentoo linux, all apps need to be compiled from source, because of the mangaged-server we have, which is good for stability. 

after some manual configuration your app is running, but not out of the box, 
some things are real bugs. 

greetings, 
daniel
On 15. Dezember 2015 at 12:20:25, Bhanu (notifications@github.com) wrote:

You can also give us your server SSH details also and we can try and check it.

**Comment by alexisskeates** [comment] 2015-12-15 12:23
So I can get the installer to show up using http://url/index.php/step1 but I assume something is still not rite it it's not working without using that url.

At the moment this is a disposable server so I could give you ssh access to it. Where should send the details to.

What I have done so far on the server is install Ubuntu 14.04 fresh with ssh enabled. Then installed the following:

sudo apt-get install apache2 php5 libapache2-mod-php5 php5-mcrypt apache2-mpm-worker mysql-server libapache2-mod-auth-mysql php5-mysql libapache2-mod-fastcgi php5-fpm php5 php5-gd php5-mysql php5-curl php5-sqlite git

Then run 

sudo a2enmod actions fastcgi alias
sudo a2enmod rewrite
sudo php5enmod mcrypt
sudo service apache2 restart

![screen shot 2015-12-15 at 12 16 01](https://cloud.githubusercontent.com/assets/10001929/11810417/dfabd328-a325-11e5-8005-75e1e94b957b.png)

**Comment by bhanu2217** [comment] 2015-12-15 12:26
If you use any web hosting company Like BlueHost, Godaddy or www.store.ladybirdwebhost.com which has pre configured Apache, PHP server with essential extension & web hosting panel like cPanel/Plesk, Faveo will works out of the box. In custom environment we can help you only if we have your server details, so we can login & test and see why the application is not working. If Laravel minimum requirement is meet Faveo will work fine.

**Comment by ayurmedia** [comment] 2015-12-15 12:26
I have all the requirements, its just the configuration needs to be changed so things work in my environment, and no i dont use ubuntu, but have a professional hosting server where i install my webapps on . if it does not work there i will use other software. 
for your testing its ok to try with ubuntu which ist the most common version. 


On 15. Dezember 2015 at 13:23:34, alexisskeates (notifications@github.com) wrote:

So I can get the installer to show up using http://url/index.php/step1 but I assume something is still not rite it it's not working without using that url.

At the moment this is a disposable server so I could give you ssh access to it. Where should send the details to.

What I have done so far on the server is install Ubuntu 14.04 fresh with ssh enabled. Then installed the following:

sudo apt-get install apache2 php5 libapache2-mod-php5 php5-mcrypt apache2-mpm-worker mysql-server libapache2-mod-auth-mysql php5-mysql libapache2-mod-fastcgi php5-fpm php5 php5-gd php5-mysql php5-curl php5-sqlite git

Then run

sudo a2enmod actions fastcgi alias
sudo a2enmod rewrite
sudo php5enmod mcrypt
sudo service apache2 restart

**Comment by alexisskeates** [comment] 2015-12-15 12:33
How should I send you ssh details. I don't want to post them in the forum

**Comment by bhanu2217** [comment] 2015-12-15 12:35
We are right now doing some R&D on if we can create Docker/Bitnami image to make it easy to install Faveo on Custom environment or virtual machines, do give us few days of time we will get back to you.

We are team of Developer and not really into server configuration but so far we have not faced issues with server environment. We usually go with Servers with WHM/cPanel so we don't have to worry about server configuration.

For PHP/Laravel application to work Apache also needs to be configured well. You can even try hosting basic/default Laravel application on your server and see if that works. If that works Faveo will also work.

**Comment by linainvers** [comment] 2015-12-15 18:20
Ubuntu 15.10 (GNU/Linux 4.2.0-19-generic x86_64) i have this problem too...

**Comment by ayurmedia** [comment] 2015-12-15 18:42
true, the installer stalled when i tried it. to fix it i copied the .htaccess mod-rewrite . index.php from a wordpress-installation, then it worked. the modrewrite is wrong.

**Comment by ayurmedia** [comment] 2015-12-15 19:31
> We are right now doing some R&D on if we can create Docker/Bitnami image to make it easy to install Faveo on Custom environment or virtual machines, do give us few days of time we will get back to you.

no, please fix the installer and don't force users to use a specific linux-version.

**Comment by linainvers** [comment] 2015-12-18 18:22
still does not work

**Comment by ayurmedia** [comment] 2015-12-18 18:35
@linainvers be more specific, where does it break ? with step1 ? then you need to try the .htaccess settings (similar to wordpress). screenshot where it stops ? you can see in my screenshot that you can install it on gentoo-linux with mysql5.6 php5.6. but still bugs are there, at least i could install it.

**Comment by linainvers** [comment] 2015-12-18 18:40
i try reinstall the software and will write later, thx for the answer

**Comment by linainvers** [comment] 2015-12-20 20:28
thank you, works fine.
Ubuntu 15.10

**Comment by ayurmedia** [comment] 2015-12-20 23:40
@linainvers good that you managed it. so my suggestion for @bhanu2217  is: 
* fix the .htaccess so the rewrite rules are correct and step1/step2 is working
* fix the .htaccess to prevent asp-tag-execution in *.blade.php templates, either in .htaccess as php_flag, or in index.php als ini_set('asp_tags',0); which should have same effect.
* extend the config for database, so that port can be entered, default it to 3306, this is possible, but only manually in the moment, also laravel does not detect "localhost:3307" which is correct notation for combined host+port

**Comment by ayurmedia** [comment] 2015-12-20 23:41
Hint: if you think faveo has too many bugs, you can also try osTicket which has way more features and is stable: http://osticket.com/download

**Comment by bhanu2217** [comment] 2015-12-21 03:45
- .htaccess redirection from non www to www is already removed in version 1.0.3.1
- Changing the installer in version 1.0.3.3 to reduce steps and simplify the UI and also add option for port no for db
- ASP tags issue we are not able to replicate for now. If the server is configured well to run Laravel application this issue will not occur

**Comment by ayurmedia** [comment] 2015-12-21 06:44
> ASP tags issue we are not able to replicate for now. If the server is configured well to run Laravel application this issue will not occur
thats just ignorant, just because you are to lazy to understand the bug you wont fix it ?  
a developer trying to install faveo does not care that it is using laravel. 
in my screenshot you can see, the bug is 100% reproducible even with php5.6. 

what is so hard to add the line: 
ini_set('asp_tags',0); 
at the beginning of index.php which seems to be your dispatcher and fix it. no need for manual "configuration" for laravel. actually laravel is causing the bug, as php allows for asp-tags, deal with it. if laravel reuses a reserved word is has to fix it, and not the user. they could have used markers without conflict. in php7 asp-tags will be removed and disabled in php, but until then people still might have old php.ini which has asp-tags on.

**Comment by bhanu2217** [comment] 2015-12-21 07:04
You can send your comment & suggestions to Laravel directly. This is not a issue and we don't think it needs any fix from our end. There is certain way & requirement Laravel works if you are not willing to follow that we cannot do much. 

Do note we are providing free support & updates out of goodwill, the language used by you throughout the conversation is very offensive in nature. It will be difficult for us to communicate and work together with this offensive nature of communication from your end.

If you want you can use this docker to configure the server to work with Laravel applications
https://github.com/mtmacdonald/docker-laravel
If you Google you will find many such ready configuration for different linux editions to work with Laravel.

For Faveo to work as expected basic Laravel requirement have to be meet. Currently Faveo is using Laravel version 5.0 and in coming months we will upgrade to Laravel 5.2

**Closed by bhanu2217** 2015-12-21 07:04 UTC
Labels: enhancement

**Comment by ayurmedia** [comment] 2015-12-21 07:07
ok, that's my last comment, and i am gone from this project. you dont care about quality, so i dont try to help you. i fixed the installer with the suggestion for the wrong htaccess. i just tell you that your aproch to "ignore" problems is wrong. bye.

**Comment by bhanu2217** [comment] 2015-12-21 07:13
We truly appreciate that you are taking out time in trying out Faveo and we will work on all issues as pointed by you or anyone but it has to be done in professional manner and language used has to be professional with respect for everyone. We have spend lot of time & energy building this product, it probably has issues but we are working on all issues at fast pace to make Faveo a world class ticket based support system. The project is active and focus is on quality now, to make it as professional, easy to use and install as possible.

**Comment by guestisp** [comment] 2015-12-21 07:54
I confirm that they don't care about quality.
I did a pull request to bring back the default laravel directory structure and it was silently closed 

Having a standard laravel structure would be better for every developers 

Actually all code is public accessibile because is placed under the document root. Laravel, as default, put codes outside document root for security reasons and this structure should be used with no "code" or "lb-faveo" directories. Il you use a framework you should deal with that and adhere to it's standard.

Even the main index.php file was customized to allow the use of a wrong directory structure!

**Comment by bhanu2217** [comment] 2015-12-21 08:16
Faveo is being used by not only by developers but many SME's & startup. It's easy for them to install Faveo when the public folder is not used, so we have followed this structure. If there is a better way of removing public from URL without changing directory structure, do share with us and we will implement it.

**Comment by guestisp** [comment] 2015-12-21 08:54
Almost all major hosting provider support "public" and "private" folders.

If you don't like this structure, probably a different framework should be used.

**Comment by bhanu2217** [comment] 2015-12-21 08:58
We want the faveo to be opened with following structure. www.yourwebsite.com and not www.yourwebsute.com/public and many a times Faveo is hosted in sub folder e.g www.yourwebsite.com/support but with default structure it will become www.yourwebsite.com/support/public if you have a better way of removing public from url do share.

**Comment by bhanu2217** [comment] 2015-12-21 09:01
I don't think there is right & wrong way, it's just choice & preference. Laravel is our choice of framework and we are using it the way we want to structure our code that works well for majority of our targeted audience. If you have better technique of hiding public in url you can share. Rather then going into choices will not lead anywhere

**Comment by guestisp** [comment] 2015-12-21 09:04
With standard Laravel structure, would be pretty easy (in fact, using www.yourwebsite.com is the default with laravel, and not  www.yourwebsite.com/public), probably a single line in htaccess. With your current directory structure I don't know.

**Comment by bhanu2217** [comment] 2015-12-21 09:09
Let me discuss with our team, we are not targeting just people with dedicated server but people using shared server and running multiple things on same domain/server. We will try and see if we can host two version of Faveo, one with standard Laravel structure and one without public. On Github we can host for advance users with default library structure and on our website offer version without public folder

**Comment by guestisp** [comment] 2015-12-21 09:16
There is a bad way: the bad way is to customize framework file to archieve an unsecure directory structure where the same could be archieved with standard structure and a single .htaccess customization

**Comment by guestisp** [comment] 2015-12-21 09:16
In your case, you are forcing ALL users to use your directory structure. The same could be applied automatically with a proper .htaccess

**Comment by bhanu2217** [comment] 2015-12-22 09:49
Directory structure has been changed to Laravel default. DB Port no option added to installer, new design installer coming soon with next release. We are also changing the work flow in next two releases to simply the ticket creation process further.

**Comment by guestisp** [comment] 2015-12-22 10:17
Well done. :clap:
