### ISSUE TITLE
Error sending attachment greater than 1 MB

### ISSUE THREAD

**Issue by 1TGBR3d** [ladybirdweb/faveo-helpdesk#6341] opened 2022-04-28 09:08 UTC
- Faveo Version : 1.11.1 Community
- PHP version : 7.1.33
- Database Driver & Version : Ver 15.1 Distrib 5.5.68-MariaDB
- Server specification : Centos 7

#### Description:
In threads page, while i'm trying to reply to a ticket, attaching pictures or PDFs bigger than 1MB, the page, after submitting form, refreshes after 2 seconds and the mail won't be sent and the attachment isn't visible in the timeline. I verified the PHP.ini file and the post and upload max file size allowed is 8MB. Can you help me to resolve this iussue?

Thank you

**Comment by bhanu2217** [comment] 2023-03-21 05:49
Please try Faveo Helpdesk Community version 2.0.0 and let us know if the issue is still occurring. For now closing the issue.

**Closed by bhanu2217** 2023-03-21 05:49 UTC
