### ISSUE TITLE
Default placeholder country code = 91

### ISSUE THREAD

**Issue by ningmu** [ladybirdweb/faveo-helpdesk#224] opened 2016-09-28 06:00 UTC
Hi there,

When you are about the submit a ticket, on the Country Code form, the default placeholder is 91.

How do I change that? I really did my best to find that default placeholder but no luck.

Thanks!

**Comment by mverma16** [comment] 2016-09-28 06:23
The country code placeholder should change according to IP address of the requester, we are using Geoip package which identifies location of the requester using his IP address and shows the country code in placeholder for that location. Can you provide us the link of your system so that we can check the issue.

**Comment by mverma16** [comment] 2016-09-28 06:30
Ok ningmu, we checked in our system and it seems that the placeholder is not working as the way it should, we'll rectify the issue ASAP. 
Thanks for notifying this issue.

**Comment by ningmu** [comment] 2016-09-28 06:38
Thanks. GeoIP shows my IP is from PH. But country code 91 is from IN. It should show 63 on mine. 

Thanks!

**Comment by mverma16** [comment] 2016-09-28 07:24
So I got the cause of this problem, updating the code now and let you know once I am done.

**Comment by mverma16** [comment] 2016-09-28 08:09
@ningmu, you can update the latest code from [this branch](https://github.com/ladybirdweb/faveo-helpdesk/pull/225), will merge this changes in next release. You can still update your system with the branch's code and check if the issue has been resolved.
Closing the issue, you can reopen it if the issue still persists in the code.

**Closed by mverma16** 2016-09-28 08:09 UTC
Labels: bug

**Comment by ningmu** [comment] 2016-09-28 09:02
@mverma16, thank you very much! after applying the said patches, it now works fine. +1: 

Thanks again! :)
