### ISSUE TITLE
C:\wamp64\www\faveo\app\Http\Controllers\Dependency\FaveoDependencyController.php on line 556

### ISSUE THREAD

**Issue by waitiong** [ladybirdweb/faveo-helpdesk#7042] opened 2022-07-27 08:54 UTC
- Faveo Version : latest
- PHP version : 7.4
- Database Driver & Version :
- Server specification :

#### Description:

May i know how i can solve this issue?

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by Sebbito** [comment] 2023-01-13 11:07
Had the same error. Firewall does allow port 80 and 443 and all extensions are installed based on the installation guide.

If you have the same stack strace like me, you can see on the line with #1 it's an SSL Error:
```
[Fri Jan 13 11:52:08.603026 2023] [proxy_fcgi:error] [pid 815] [client 91.67.79.147:63992] AH01071: Got error 'PHP message: PHP Warning:
fopen(https://helpdesk.netstack.de/cron-test.php): Failed to open stream: Connection refused in /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php on line 555
PHP message: PHP Fatal error:  Uncaught TypeError: stream_context_get_params(): Argument #1 ($context) must be of type resource, bool given in /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php:556
Stack trace:
#0 /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php(556): stream_context_get_params()
#1 /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php(196): App\\Http\\Controllers\\Dependency\\FaveoDependencyController->checkSSLCertificateOnDomain()
#2 /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php(129): App\\Http\\Controllers\\Dependency\\FaveoDependencyController->requisitesWithTheirStatus()
#3 /var/www/faveo/public/probe.php(146): App\\Http\\Controllers\\Dependency\\FaveoDependencyController->validateRequisites()
#4 {main}
thrown in /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php on line 556'
```

I was missing the SSL Step. Then it was able to complete the check.

If you have a different error, please post the error log located according to the place in your apache2 configuration.

**Comment by Sebbito** [comment] 2023-01-13 11:08
Had the same error. Firewall does allow port 80 and 443 and all extensions are installed based on the installation guide.

If you have the same stack strace like me, you can see on the line with #1 it's an SSL Error:
```
[Fri Jan 13 11:52:08.603026 2023] [proxy_fcgi:error] [pid 815] [client 91.67.79.147:63992] AH01071: Got error 'PHP message: PHP Warning:
fopen(https://example.com/cron-test.php): Failed to open stream: Connection refused in /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php on line 555
PHP message: PHP Fatal error:  Uncaught TypeError: stream_context_get_params(): Argument #1 ($context) must be of type resource, bool given in /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php:556
Stack trace:
#0 /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php(556): stream_context_get_params()
#1 /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php(196): App\\Http\\Controllers\\Dependency\\FaveoDependencyController->checkSSLCertificateOnDomain()
#2 /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php(129): App\\Http\\Controllers\\Dependency\\FaveoDependencyController->requisitesWithTheirStatus()
#3 /var/www/faveo/public/probe.php(146): App\\Http\\Controllers\\Dependency\\FaveoDependencyController->validateRequisites()
#4 {main}
thrown in /var/www/faveo/app/Http/Controllers/Dependency/FaveoDependencyController.php on line 556'
```

I was missing the SSL Step. Then it was able to complete the check.

If you have a different error, please post the error log located according to the place in your apache2 configuration.

**Comment by bhanu2217** [comment] 2023-03-21 05:46
Please try Faveo Helpdesk Community version 2.0.0 and let us know if the issue is still occurring. For now closing the issue.

**Closed by bhanu2217** 2023-03-21 05:46 UTC
