### ISSUE TITLE
We are not able to login faveo with Reseller Id and Password.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/faveo-helpdesk#394] opened 2017-01-28 07:08 UTC
This is our Reseller username **saifu78692@outlook.com** and password **demopass12345** . We are able to login in reseller but in faveo we are not able to login getting below error.Please check ASAP.

![captur1e](https://cloud.githubusercontent.com/assets/18435376/22394997/f92b8406-e555-11e6-8d4a-99fdd203dfff.PNG)

I have tested from Master branch of faveohelpdesk.

**Comment by SarfrazS** [comment] 2017-01-28 07:20
After actived reseller plugin we are not able to create ticket from client panel. Please see the below Image 
while creating ticket showing this message.

![capture](https://cloud.githubusercontent.com/assets/18435376/22395067/3b1e1b10-e558-11e6-89d4-82c8c0875640.PNG)

**Comment by SarfrazS** [comment] 2017-01-28 09:01
We add customer on Reseller, It should come in faveo but not coming. Because while we register in faveo user also come in reseller.

**Comment by vijaysebastian** [comment] 2017-03-17 10:53
duplicate of #380

**Closed by vijaysebastian** 2017-03-17 10:53 UTC
Labels: bug, Need tester's feedback
