### ISSUE TITLE
Clear dummy data button not working

### ISSUE THREAD

**Issue by EgyptianM** [ladybirdweb/faveo-helpdesk#6533] opened 2022-05-23 20:23 UTC
- Faveo Version : Version Community 1.11.1
- PHP version : 7.4
- Database Driver & Version : MySql
- Server specification : apache

#### Description:

after checking the ` Yes I want to clean dummy data`  check box the buttons state doesn't change to enabled
#### Steps To Reproduce:

Install fresh copy with `demodatabase.sql` and go to clean dummy data and try to clear

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by bhanu2217** [comment] 2023-03-21 05:49
Please try Faveo Helpdesk Community version 2.0.0 and let us know if the issue is still occurring. For now closing the issue.

**Closed by bhanu2217** 2023-03-21 05:49 UTC

**Comment by hs-champi** [comment] 2023-12-06 09:03
Hi, the issue is still present with faveo 2.0.3

![image](https://github.com/ladybirdweb/faveo-helpdesk/assets/153071280/6bace864-0a2c-4d2e-97c4-471bce33a224)

maybe it's based on this js issue:
![image](https://github.com/ladybirdweb/faveo-helpdesk/assets/153071280/85681e46-5629-47db-a309-0da2dd2f12a0)

![image](https://github.com/ladybirdweb/faveo-helpdesk/assets/153071280/59f090f3-e66a-4f84-b229-eb32a8f100dd)
