### ISSUE TITLE
Compose.json is messed , None of the php version is able to resolve dependencies

### ISSUE THREAD

**Issue by ubxty** [ladybirdweb/faveo-helpdesk#6755] opened 2022-06-16 07:13 UTC
- Faveo Version : #.#.#
- PHP version :
- Database Driver & Version :
- Server specification :

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [x] release-tag

**Comment by bhanu2217** [comment] 2023-03-21 05:48
Please try Faveo Helpdesk Community version 2.0.0 and let us know if the issue is still occurring. For now closing the issue.

**Closed by bhanu2217** 2023-03-21 05:48 UTC
