### ISSUE TITLE
On Ticket reply other replies go blank

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#279] opened 2016-10-30 07:04 UTC
**Version:** 1.0.8.0 RC
**Browser:** Chrome

**Issue:**
When agent replies to ticket from agent panel. Other previous customer iframe replies go blank

**Comment by bhanu2217** [comment] 2016-10-30 07:06
**Screenshot:**
![screen shot 2016-10-29 at 6 54 08 pm](https://cloud.githubusercontent.com/assets/240898/19834984/5462c942-9e9d-11e6-8aa2-4460d00090b4.png)

**Comment by mverma16** [comment] 2016-11-29 08:26
fixed, @SarfrazS  please test.

**Comment by SarfrazS** [comment] 2016-12-07 10:53
I have tested in version 1.0.8.0 RC from Development branch not looking correct. Please check it.

**Comment by mverma16** [comment] 2017-03-06 09:46
Closing the issue as it appears to be a duplicate of [#433](https://github.com/ladybirdweb/faveo-helpdesk/issues/433)

**Closed by mverma16** 2017-03-06 09:46 UTC
Labels: bug
