### ISSUE TITLE
 Class 'Bugsnag' not found error

### ISSUE THREAD

**Issue by sprklinginfo** [ladybirdweb/faveo-helpdesk#6732] opened 2022-06-14 03:30 UTC
- Faveo Version : latest 
- PHP version : 7.2.34
- Database Driver & Version :
- Server specification : ubuntu 20.04

#### Description:
After running 'composer install' or 'php artisan' command. but when I check the 'vendor' folder, I can see a ' bugsnag' folder with two sub-folders inside: 'bugsnag' and 'bugsnag-laravel'

#### Steps To Reproduce:

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Fatal error:  Uncaught Error: Class 'Bugsnag' not found in /home/helpdesk/public_html/faveo-helpdesk/app/Exceptions/Handler.php:50
Stack trace:
#0 /home/helpdesk/public_html/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 {main}
  thrown in /home/helpdesk/public_html/faveo-helpdesk/app/Exceptions/Handler.php on line 50
PHP Fatal error:  Uncaught Error: Class 'Bugsnag' not found in /home/helpdesk/public_html/faveo-helpdesk/app/Exceptions/Handler.php:50
Stack trace:
#0 /home/helpdesk/public_html/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#1 /home/helpdesk/public_html/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
```

#### Downloaded from
- [ X] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by bhanu2217** [comment] 2023-03-21 05:49
Please try Faveo Helpdesk Community version 2.0.0 and let us know if the issue is still occurring. For now closing the issue.

**Closed by bhanu2217** 2023-03-21 05:49 UTC
