### ISSUE TITLE
Languages...The agents can not erase a ticket

### ISSUE THREAD

**Issue by zku7** [ladybirdweb/faveo-helpdesk#470] opened 2017-05-10 16:52 UTC
- Faveo Version :1.94
- PHP version :5.6.30
- Database Driver & Version :mysql
- Server specification :

#### Description:
Faveo community....The agents can not erase a ticket..only with the English language they can.

#### Downloaded from
- [ x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment] 2017-05-11 04:48
Closing the issue as it appears to be duplicate of #377

**Closed by mverma16** 2017-05-11 04:48 UTC
