### ISSUE TITLE
See error 500 by ticket

### ISSUE THREAD

**Issue by csaeum** [ladybirdweb/faveo-helpdesk#98] opened 2016-06-29 09:37 UTC
Have just a ticket make, I have the store to get an error. Sorry have not written him.

Then, recalling the ticket I get the error in the screenshot.
Other tickets go without problems even to look at.

For me now unclear went the mail out to the customer?
The ticket is available in the database but I can call it via the backend no longer.

On what it could be?

![faveo-ticket](https://cloud.githubusercontent.com/assets/1543510/16447524/5a05c2b6-3ded-11e6-826c-7f7830dd186f.png)

**Comment by sujit223** [comment] 2016-06-30 05:18
Hi Cris,
This looks some what serious issue. Need some details from you to fix this.

**Comment by bhanu2217** [comment] 2016-06-30 06:01
Can you let us know the steps and how this issue occurred, so we can troubleshoot further

**Comment by csaeum** [comment] 2016-06-30 11:18
The steps were very simple.

1. Create Ticket
2. User Email and Username
3. Text on the User
4. Create Ticket

then came a mistake I not listed. SORRY

When I wanted to watch the ticket, the 500 came. The ticket is present in the database. But I can not watch over Faveo.
I then again the same ticket created and there went the mail out.
Strange is also that we get no more mails although that are in the mailbox yesterday.
Can it be that he has carried out at the same moment a CronJob and it therefore came to the error
Have you already sent to a ticket.

**Comment by csaeum** [comment] 2016-06-30 14:09
Ok found errors, apparently the form has not been evaluated properly and thus the ticket was indeed registered in the DB but without DEPT_ID

Have here now the standard DEPT_ID registered and now it's back.

**Comment by sujit223** [comment] 2016-06-30 14:25
So we had found this bug too. But didn't expected that this was the cause. Also this bug have been fixed in 1.0.7.9 but there are more fixing we are working on.

**Comment by mbiolsi** [comment] 2016-07-08 14:48
Yes, I can verify the same. HOWEVER, the problem for me was that I had a Help Topic that was not assigned to a Department. IF all of your Help Topics have Departments, this should not throw an error.

Admin -> Manage -> Help Topics
http://screencast.com/t/dA5QnbcQyH

**Comment by mathieu-aubin** [comment] 2016-07-10 06:07
Hi,
I strongly suggest using [pastebins](http://awk.freeshell.org/ListOfPastebins) or even [github's gists](https://gist.github.com/) to post error codes.

You can also use markdown code straight here...

```php
<?php
$phpCode = "yes it highlights and makes it all pretty";
echo $phpCode;
?>
```

That way it makes them easily searchable and results in less efforts from the support team and the community.

Just a suggestion that i think should be considered.

**Comment by mathieu-aubin** [comment] 2016-07-10 06:10
@mbiolsi -- [your panel](http://screencast.com/t/dA5QnbcQyH) looks neat, almost sexy hahahha  :+1:

**Comment by mbiolsi** [comment] 2016-07-11 18:37
haha. Thanks @mathieu-aubin The user [PORTAL ](https://help.coughlin.co/)got a little bit of a makeover as well thanks to some custom CSS.

**Closed** 2016-08-31 09:04 UTC
