### ISSUE TITLE
Dependency Version Error

### ISSUE THREAD

**Issue by maviterlikli** [ladybirdweb/faveo-helpdesk#7623] opened 2022-12-30 13:48 UTC
- Faveo Version : [v1.11.1]
- PHP version : 7.1.3 and 7.4
- Database Driver & Version : Not relevant
- Server specification : Docker php-alpine

#### Description:
When composer update is run (or composer install) there is an impossible version depency to be met. 
phpspec/phpspec8[4.0.0, ..., 4.0.3] limits upper php version to 7.2.
However,
tymon/jwt-auth dev-develop requires php version to be above 7.4

Since php version cannot be smaller than 7.2 and higher than 7.4 at the same time, it is impossible to run composer. 

#### Steps To Reproduce:
1. Pull docker image php with tag 7.1.3-fpm-alpine and 7.4-fpm-alpine.
2. Pull master repo v1.11.1 from github
3. Install composer.phar [Download Page & Steps](https://getcomposer.org/download/)
4. Run  `php composer.phar update`
5. Get errors from different php versions given in 1st step.
Error output;
![Error output](https://user-images.githubusercontent.com/95472396/210076892-bf8c1469-17aa-496d-aaab-ea4f78722148.png)
#### Downloaded from
- [ ] master-branch

**Comment by bhanu2217** [comment] 2023-03-21 05:47
Please try Faveo Helpdesk Community version 2.0.0 and let us know if the issue is still occurring. For now closing the issue.

**Closed by bhanu2217** 2023-03-21 05:47 UTC
